### ISSUE TITLE
feTS not working with cloudflare worker

### ISSUE THREAD

**Issue by francelwebdev** [ardatan/feTS#756]
feTS not working with cloudflare worker. I got 302 Found redirected to /docs with blank page.

**Comment by Urigo** [comment]
@francelwebdev can you share a reproduction?


For now I'm labeling this according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow) to `stage 0`.

Now in order to advance to `stage 1` we'll need a simple reproduction, maybe in code-sandbox.

Later to progress to `stage 2`, a failing test would be needed, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by ardatan** [comment]
Now we have a landing page instead of redirection. This should be fixed in the latest version. Closing the issue for now. If you still have the issues, let's know!
