### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by thelinuxlich** [ardatan/feTS#760]
I want to add the createClient return type to a interface, however it gives me this error

```ts
declare module 'vitest' {
	export interface TestContext {
		client: Awaited<ReturnType<typeof createClient>>
	}
}
```

Result when consuming the context:

![image](https://github.com/ardatan/feTS/assets/5043/78b9a1d5-b90b-4e55-a6b0-ea6a754cf64b)

I don't have a lot of endpoints so I wonder if this error won't appear in other places too

**Comment by ardatan** [comment]
`createClient` doesn't return a promise, so I don't think you need `Awaited` there, and the return type of `createClient` is too dynamic to be used in that way. 
 I'd recommend to use these types instead of `ReturnType`;
 https://github.com/ardatan/feTS/blob/master/packages/fets/src/client/createClient.ts#L68C4-L68C13

**Comment by thelinuxlich** [comment]
Ohhh my bad, actually removing Awaited made it work!
