### ISSUE TITLE
passing formData doesn't change the content-type to "multipart/form-data"

### ISSUE THREAD

**Issue by thelinuxlich** [ardatan/feTS#901]
Even adding "multipart/form-data" to requestBody.content in OpenAPI spec doesn't make feTS change the content-type like the docs say here: https://the-guild.dev/openapi/fets/client/request-params#form-data--file-uploads

**Comment by ardatan** [comment]
Thank you @thelinuxlich for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 0`.

Now in order to advance to `stage 1` we'll need a simple reproduction, maybe in code-sandbox? 

Later to progress to `stage 2`, a failing test would be needed, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by thelinuxlich** [comment]
Gonna close it because it's not feTS responsibility to do this
